services:
  redis:
    image: redis:8-alpine
    container_name: redis

  dashboard:
    build:
      context: .
      dockerfile: docker/dashboard/Dockerfile

    container_name: dashboard

    depends_on:
      - redis

    ports:
      - "8000:8000"

  receiver-1:
    build:
      context: .
      dockerfile: docker/receiver/Dockerfile

    container_name: receiver-1

    ports:
      - "9001:8000"

  receiver-2:
    build:
      context: .
      dockerfile: docker/receiver/Dockerfile

    container_name: receiver-2

    ports:
      - "9002:8000"

  receiver-3:
    build:
      context: .
      dockerfile: docker/receiver/Dockerfile

    container_name: receiver-3

    ports:
      - "9003:8000"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile

    container_name: nginx

    depends_on:
      - receiver-1
      - receiver-2
      - receiver-3

    ports:
      - "8080:80"

  generator-1:
    build:
      context: .
      dockerfile: docker/generator/Dockerfile

    container_name: generator-1

    environment:
      GENERATOR_NAME: generator-1

    ports:
      - "9101:8000"

    depends_on:
      - redis
      - nginx

  generator-2:
    build:
      context: .
      dockerfile: docker/generator/Dockerfile

    container_name: generator-2

    environment:
      GENERATOR_NAME: generator-2

    ports:
      - "9102:8000"

    depends_on:
      - redis
      - nginx

  generator-3:
    build:
      context: .
      dockerfile: docker/generator/Dockerfile

    container_name: generator-3

    environment:
      GENERATOR_NAME: generator-3

    ports:
      - "9103:8000"

    depends_on:
      - redis
      - nginx

  prometheus:
    image: prom/prometheus:v3.5.0

    container_name: prometheus

    command:
      - --config.file=/etc/prometheus/prometheus.yml

    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:2.9.8

    command:
      - -config.file=/etc/loki/config.yml

    volumes:
      - ./observability/loki/config.yml:/etc/loki/config.yml
      - loki-data:/loki

    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.8

    command: -config.file=/etc/promtail/config.yml

    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./observability/promtail/config.yml:/etc/promtail/config.yml

    depends_on:
      - loki

  tempo:
    image: grafana/tempo:2.5.0

    command:
      - -config.file=/etc/tempo.yml

    volumes:
      - ./observability/tempo/tempo.yml:/etc/tempo.yml

    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"

volumes:
  grafana_data:
  loki-data:
