apiVersion: v1
kind: ConfigMap

metadata:
  name: grafana-datasources
  namespace: observability

data:
  datasources.yaml: |
{{ .Files.Get "observability/grafana/provisioning/datasources/datasources.yaml" | indent 4 }}
