apiVersion: apps/v1
kind: Deployment

metadata:
  name: otel-collector
  namespace: {{ .Values.namespace }}

spec:

  replicas: {{ .Values.otelCollector.replicas }}

  selector:

    matchLabels:

      app: otel-collector

  template:

    metadata:

      labels:

        app: otel-collector

    spec:

      containers:

        - name: otel-collector

          image: "{{ .Values.otelCollector.image }}:{{ .Values.otelCollector.tag }}"

          args:

            - "--config=/etc/otel/collector.yml"

          ports:

            - containerPort: 4317

            - containerPort: 4318

          volumeMounts:

            - name: config

              mountPath: /etc/otel

      volumes:

        - name: config

          configMap:

            name: otel-collector-config
