apiVersion: v1
kind: Service

metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}

spec:
  type: {{ .Values.service.prometheus.type }}

  selector:
    app: prometheus

  ports:
    - port: {{ .Values.service.prometheus.port }}
      targetPort: 9090
      protocol: TCP
