global:
  scrape_interval: 5s

scrape_configs:
  - job_name: generators

    static_configs:
      - targets:
          - generator-1:8000
          - generator-2:8000
          - generator-3:8000

  - job_name: receivers

    static_configs:
      - targets:
          - receiver-1:8000
          - receiver-2:8000
          - receiver-3:8000
