global:
  scrape_interval: 5s

scrape_configs:
  - job_name: generators

    kubernetes_sd_configs:
      - role: pod

    relabel_configs:
      - source_labels:
          - __meta_kubernetes_namespace
        regex: telemetry
        action: keep

      - source_labels:
          - __meta_kubernetes_pod_label_app
        regex: generator
        action: keep

      - source_labels:
          - __meta_kubernetes_pod_ip
        target_label: __address__
        replacement: $1:8000

  - job_name: receivers

    kubernetes_sd_configs:
      - role: pod

    relabel_configs:
      - source_labels:
          - __meta_kubernetes_namespace
        regex: telemetry
        action: keep

      - source_labels:
          - __meta_kubernetes_pod_label_app
        regex: receiver
        action: keep

      - source_labels:
          - __meta_kubernetes_pod_ip
        target_label: __address__
        replacement: $1:8000
