namespace: observability

prometheus:
  image: prom/prometheus
  tag: v3.5.0
  replicas: 1

grafana:
  image: grafana/grafana:12.0.2
  replicas: 1
  adminUser: admin
  adminPassword: admin

loki:
  image: grafana/loki
  tag: 3.5.2
  replicas: 1

promtail:
  image: grafana/promtail
  tag: 3.5.2
  replicas: 1

tempo:
  image: grafana/tempo
  tag: 2.8.1
  replicas: 1

otelCollector:
  image: otel/opentelemetry-collector-contrib
  tag: 0.130.0
  replicas: 1

service:
  prometheus:
    type: ClusterIP
    port: 9090

ingress:
  prometheus:
    enabled: true
    host: prometheus.local

resources:
  prometheus:
    cpu: 200m
    memory: 512Mi

storage:
  prometheus:
    enabled: false
    size: 5Gi
