events {}

http {

    upstream receivers {

        server receiver-1:8000;
        server receiver-2:8000;
        server receiver-3:8000;

    }

    server {

        listen 80;

        location /receive {

            proxy_pass http://receivers;

        }

        location /health {

            return 200 "ok";
        }
    }
}
