events {}

http {

    upstream receivers {

        server receiver:80;

    }

    server {

        listen 80;

        location /receive {

            proxy_pass http://receivers;

        }

        location /health {

            return 200 "ok";
        }
    }
}
