apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-config
  namespace: telemetry
  labels:
    {{- include "telemetry.labels" . | nindent 4 }}

data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RECEIVER_URL: http://nginx/receive
  LOG_LEVEL: INFO
