namespace: telemetry

image:
  generator: ghcr.io/onerohandesai/telemetry-generator
  receiver: ghcr.io/onerohandesai/telemetry-receiver
  dashboard: ghcr.io/onerohandesai/telemetry-dashboard
  nginx: ghcr.io/onerohandesai/telemetry-nginx
  redis: redis:7-alpine

imageTag: main

replicas:
  generator: 3
  receiver: 3
  dashboard: 1
  nginx: 1
  redis: 1

service:
  type: ClusterIP

ingress:
  enabled: true
  host: telemetry.local

config:
  redisHost: redis
  redisPort: "6379"
  receiverUrl: http://nginx/receive
  otelEndpoint: http://tempo:4318
  logLevel: INFO

resources:
  generator:
    cpu: 100m
    memory: 128Mi
  receiver:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

  minReplicas: 3
  maxReplicas: 10

  targetCPUUtilizationPercentage: 60

pdb:
  enabled: true
  minAvailable: 2
