- name: Install Docker
  shell: curl -fsSL https://get.docker.com | sh

- name: Enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
