apiVersion: v1
kind: ConfigMap

metadata:
  name: telemetry-config
  namespace: telemetry

data:
  REDIS_HOST: redis

  REDIS_PORT: "6379"

  RECEIVER_URL: http://nginx/receive

  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318

  LOG_LEVEL: INFO
