apiVersion: v1
kind: ConfigMap

metadata:
  name: nginx-config
  namespace: telemetry

data:
  nginx.conf: |
    events {}

    http {

      upstream receivers {

        server receiver:8000;

      }

      server {

        listen 80;

        location /receive {
          proxy_pass http://receivers;
        }

        location /health {
          return 200 "ok";
        }

      }

    }
