name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  validate:
    name: Validate Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest

      - name: Run Ruff
        run: ruff check .

      - name: Run Pytest
        run: pytest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Generator
      - name: Build Generator Image
        run: |
          docker build \
            -t telemetry-generator:ci \
            -f docker/generator/Dockerfile .

      - name: Scan Generator Image
        uses: aquasecurity/trivy-action@0.36.0
        with:
          image-ref: telemetry-generator:ci
          format: table
          exit-code: "1"
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Generate Generator SBOM
        uses: anchore/sbom-action@v0
        with:
          image: telemetry-generator:ci
          output-file: generator-sbom.spdx.json

      # Receiver
      - name: Build Receiver Image
        run: |
          docker build \
            -t telemetry-receiver:ci \
            -f docker/receiver/Dockerfile .

      - name: Scan Receiver Image
        uses: aquasecurity/trivy-action@0.36.0
        with:
          image-ref: telemetry-receiver:ci
          format: table
          exit-code: "1"
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Generate Receiver SBOM
        uses: anchore/sbom-action@v0
        with:
          image: telemetry-receiver:ci
          output-file: receiver-sbom.spdx.json

      # dashboard
      - name: Build Dashboard Image
        run: |
          docker build \
            -t telemetry-dashboard:ci \
            -f docker/dashboard/Dockerfile .

      - name: Scan Dashboard Image
        uses: aquasecurity/trivy-action@0.36.0
        with:
          image-ref: telemetry-dashboard:ci
          format: table
          exit-code: "1"
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Generate Dashboard SBOM
        uses: anchore/sbom-action@v0
        with:
          image: telemetry-dashboard:ci
          output-file: dashboard-sbom.spdx.json

      # Nginx
      - name: Build Nginx Image
        run: |
          docker build \
            -t telemetry-nginx:ci \
            -f docker/nginx/Dockerfile .

      - name: Scan Nginx Image
        uses: aquasecurity/trivy-action@0.36.0
        with:
          image-ref: telemetry-nginx:ci
          format: table
          exit-code: "1"
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Generate Nginx SBOM
        uses: anchore/sbom-action@v0
        with:
          image: telemetry-nginx:ci
          output-file: nginx-sbom.spdx.json

      # Upload SBOMs
      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-files
          path: |
            generator-sbom.spdx.json
            receiver-sbom.spdx.json
            dashboard-sbom.spdx.json
            nginx-sbom.spdx.json
